version: '3.9'

services:
  app:
    build: src/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME_DB__uri=postgresql://postgres:postgres@db:5432/upskill
      - PROJECT_NAME_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    image: postgres:14-alpine3.16
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DBS=upskill
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
